### ISSUE TITLE
Template repositories for common arfc repo types. 

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#160]
## I'm submitting a ...
  - [x] feature request

## Expected Behavior

There is a way to create templates for new repositories in one's GitHub organization, so that each new repository contains what is expected as soon as it is created. 

https://help.github.com/en/articles/creating-a-template-repository

This is a great opportunity to improve our workflow for new repositories. I suppose there should be template repository for : 

- [x] presentations
- [x] journal articles
- [x] technical reports
- [x] conference papers
- [x] software projects
- [x] poster (latex pls)

It's possible that the first four could be captured in a single template with subfolders that can be deleted by the user during the first moment. 

Ideally, all repositories in this org should have a handful of key things (readme, license file, contributors document, proper issue labels, etc.). Presentations should stem from the arfc presentation template (maybe that repository should just become the template for others?)

## Actual Behavior

no templates exist. 

## How can this issue be closed?

This issue can be closed when template repositories are available which can generate repositories with all the expected stuff in them. 

Steps:
- [ ] Understand templates repositories
- [ ] Determine a checklist of things that each repository template type requires (work with Prof. Huff)
- [ ] Create templates for each type
- [ ] Make a PR to this repository adding an arfc manual guide for using these templates.
- [ ] close this issue when your PR is merged.

**Comment by katyhuff** [comment]
Maybe an undergraduate would be interested in doing this work (@kipk49 @aruzzo @datw0258 @nathanb01 )

**Comment by katyhuff** [comment]
Same hopes, new summer! @datw0258 @Dayvis7 @nsryan2 ... anyone interested? The presentations and journal articles templates have been created. Now it's time to think about conference papers, etc.

**Comment by katyhuff** [comment]
Maybe someone who is considering submitting an ANS summary (@samgdotson @robfairh @ZoeRichter?) would be interested in making an ANS summary template with the ANS .cls file, etc....

**Comment by nsryan2** [comment]
I have a couple templates that I was working on for the Student Conference 2021 (before it was changed to 2022), I think they would fit the purpose that this issue describes. They are currently .docx files (I think), but I can format them into LaTex and make a template repository from them.

**Comment by samgdotson** [comment]
@nsryan2 No need to create a format in LaTex from a word document. ANS has a LaTeX template that we can just turn into a repository. In fact, I already have. 

This is closed by #1 in ``ans-abs-template``

**Comment by nsryan2** [comment]
Awesome, I'm looking at your pull request right now

**Comment by nsryan2** [comment]
There is a [report-template](https://github.com/arfc/report-template) repository, and from what I can tell it seems to align with the technical report template requested in this issue. Would adding instructions on how to initialize it to the ARFC report page, and the README.md in the repository file be a good next step?

**Comment by samgdotson** [comment]
Seems appropriate to me.
