### ISSUE TITLE
Course Planning and Registration Checklist

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#173]
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [ ] bug report
  - [x] feature request
  - [ ] question

## Expected Behavior
The website should have a checklist to let students know how and where to register for classes, what classes to register for, etc.

## Actual Behavior
No such checklist is available. 

## How can this issue be closed?
This issue can be closed with a Pull Request that adds a checklist regarding how students can handle planning their curriculum, registering for courses, etc.

**Comment by katyhuff** [comment]
Here are some thoughts on this checklist. 
Undergraduate students should meet semesterly with their faculty advisor (sometimes that's Katy, sometimes not). For that meeting, the student should bring a recent copy of their DARS report and a plan for the semester. Follow the recommended curriculum pathway at npre.illinois.edu . 

For graduate students in ARFC: 
- Review the course requirements for the MS and PhD online (link).
- Every graduate student will have a google drive folder that is shared only between them and Katy. 
- In that google drive folder there is a Student Plan. It's a spreadsheet of courses, like so.
![image](https://user-images.githubusercontent.com/393899/84724236-44cf4b80-af4d-11ea-9ac4-8ce729b72679.png)
- Near the end of each semester, before registration opens (Gavin, please include an indication of when this happens), graduate students should fill out this plan for the upcoming semester and discuss it with Prof. Huff.
- Early on, Research Assistantship students typically take 2 or 3 graduate classes per semester and take between 4 and 8 research credit hours (Section KH?). 
- Later in graduate school, students typically take 1 or fewer graduate classes per semester and take as many research credits as necessary to comprise a full load (12 credits? 16 credits? I honestly can never remember)
- Once Prof. Huff has approved the course plan in your Student Record, you can request that the registration hold be lifted  so that you can go ahead and register for classes. To do so, send a polite email to the student office in NPRE (specifically, the graduate student advisor staff member in NPRE), CC'ing Prof. Huff, with a pdf copy of your student record document attached. Let the staff member know that we have discussed the attached course plan, I have approved it, and you would like the registration hold lifted (please and thank you).
- Then, register. I honestly have no idea how this works. I think you log into student self service? After that, I haven't the foggiest idea.
- Near the beginning of each semester, students should update their Student Record with the grades they've earned in the courses from the past semester.

**Comment by Dayvis7** [comment]
@katyhuff I'm trying to put the image of the example plan into a page, but the picture is much too big. I saw that one of the ways to change sizing was to take the file name then include ` =size1xsize2`. Every time I do though, the picture won't show. Do you have a size recommendation or a better method I should try?

**Comment by katyhuff** [comment]
I'm not sure what you mean by "take the file name then include =size1xsize2 ".  Do you mean in the markdown file like so https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown? 

If so, that won't work. While it may have worked for the OP, it won't work for everyone. The more comprehensive and general answer is the [answer with more points on that same page](https://stackoverflow.com/a/14747656). Try that (don't be afraid to keep trying if at first you don't succeed!)
