### ISSUE TITLE
Look for additional items to add to the writing checklist. 

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#193]
This is a straightforward task appropriate for an undergraduate. 
I have reviewed tons of student documents over time. I'm sure there are comments that I repeat frequently, but which don't yet appear on the writing checklist. I was thinking :

- I could share some of those old reviews with you,
- You could peruse my scribbles 
- You could identify comments I make frequently or which could be added to the checklist.
- And you could add those items to the writing checklist.

This isn't urgent, but maybe @Dayvis7 would be appropriate for it if he has time this summer? Whomever wants to do this task, please let me know and I'll point you to the old reviews.

**Comment by Dayvis7** [comment]
I could try to look it over! You're saying just to find common suggestions and add them to the official checklist? That sounds easy enough.

**Comment by katyhuff** [comment]
Yep, I'll slack message a link with a bunch of old reviewed pdfs so you can get started whenever you like.

**Comment by Dayvis7** [comment]
@katyhuff what do you think of these?
 	-Each sentence/paragraph should logically follow the previous sentence/paragraph
	-Concise language - If you're going to say something, don't beat around the bush
	-Cite, Cite, Cite. Cite images, software, anything of that nature
	-When making examples, use variables instead of numbers, or use symbols/math characters instead of acronyms
	-Italicize words or phrases distinct to your work
	-You're a human writing for other humans: Make the wording exciting, and remember some people reading it
		won't know as much as you do. Be specific, yet general enough for others to know.
	-If you're using an uncommon word, either consider changing it or define it in its first usage.
	-Don't repeat yourself too much. Using the same phrase every few paragraphs gets boring

**Comment by katyhuff** [comment]
these look great!!! Thanks @Dayvis7 !
