### ISSUE TITLE
Difference between arfc.github and arfc.npre

### ISSUE THREAD

**Issue by nsryan2** [arfc/arfc.github.io#200]
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

## Expected Behavior
It seems that arfc.github.io should be the same as arfc.npre.illinois.edu in all respects.

## Actual Behavior
Links on arfc.npre.illinois.edu are broken, many of the guides don't show up as links (rather as text). It seems that arfc.github.io is more up-to-date than arfc.npre.illinois.edu. Something else that's missing, besides links and pages, is the block I logo in the navbar.

## Steps to Reproduce the Problem

  1. Open [arfc.github.io](https://arfc.github.io) and [arfc.npre.illinois.edu](https://arfc.npre.illinois.edu)
  1. Check the behavior of the link to "People" and take a look at the guides

## How can this issue be closed?
This issue can be closed when the process for updating arfc.npre.illinois.edu is outlined and a part of the workflow for updates to arfc.github.io. Additionally, the differences between the two as they currently exist should be reconciled.

**Comment by nsryan2** [comment]
I'm not sure what changed, but they have been reconciled.

**Comment by katyhuff** [comment]
Sorry - I should have left a comment here. They are kept in sync by a cron job on the Illinois servers. Periodically, that cron job fails. When that happens, it stops updating. Your issue alerted me to the need to go restart the cron job. 

I think that there may still be an issue with some of the links though.... that crops up sometimes.
