### ISSUE TITLE
Bad hyperlink URLs in Moltres part of website

### ISSUE THREAD

**Issue by yardasol** [arfc/arfc.github.io#206]
## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

## Expected Behavior
In the Moltres part of the website, the URL of any hyperlink that intends to direct a user to a resource on the MOOSE website should correspond to said resource. Clicking on this link takes the user to the intended resource.

## Actual Behavior
In the Moltres part of the website, the URL of many hyperlinks that intend to direct a user to resources on the MOOSE website do not correspond to said resources. Clicking on these links returns a 404 Not Found error.
## Steps to Reproduce the Problem

  1. Go to [the Moltres part of the website](http://arfc.github.io/software/moltres/) and all of its related pages (wiki, input example, etc.)
  2. Click on any hyperlink that appears to direct a user to a resource on the MOOSE website.

## Specifications
 - Brower: Firefox v81.0 (64-bit)

## How can this issue be closed?

This issue can be closed when all hyperlinks have URLs that correspond to the appropriate resource on the MOOSE website.

**Comment by katyhuff** [comment]
Thanks for noticing. 
Cause: MOOSE has changed their website layout. What used to be in the wiki is now in main menu content. Here are some links to replace the current ones with: 

Main page (not a wiki:) mooseframework.org
Tutorial: https://www.mooseframework.org/workshop/#/
Examples: https://www.mooseframework.org/examples/index.html
