### ISSUE TITLE
Update MOOSE & Moltres on BW

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#213]
The existing MOOSE (framework) and Moltres (app) as well as submodules (e.g. Squirrel) may need to be updated on Blue Waters in the group (bbcc) shared directory. This may include an update to files like a .moose_profile file in the group directory that will allow users to more easily access and use the moose compilers.

## How can this issue be closed?

This issue can be closed by following the instructions at [the moose framework site](https://mooseframework.inl.gov/getting_started/installation/hpc_install_moose.html) and customizing those instructions for the compilers and modules (e.g. python) on Blue Waters [details here](https://bluewaters.ncsa.illinois.edu/compiling) so that the moose compilers are built and all repos are updated in the bbcc shared space for use by all arfc members.

**Comment by smpark7** [comment]
I've updated MOOSE and Moltres on BW. I created an ```env/``` directory to hold the ```moose_env``` file and other future env files. The ```projects``` directory also contains a ```readme.md``` file detailing the instructions for installing and updating Moltres on BW.

You may review the ```readme.md``` and ```moose_env``` files [here](https://gist.github.com/smpark7/40cb207dff9b633bd77d439a9d158a20).

**Comment by smpark7** [comment]
@katyhuff I've updated Moltres on BW again for the latest changes since I last touched it. Can I close this issue?

**Comment by katyhuff** [comment]
Yep!
