### ISSUE TITLE
Add Guide for Theta

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#215]
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [x] feature request

## Expected Behavior
Ideally, just like there is a [Using Blue Waters](http://arfc.github.io/manual/guides/bluewaters) page on the arfc site, there should be a Using Theta page (perhaps at http://arfc.github.io/manual/guides/theta). It should describe where to go to request an account, where to find information about logging in, and eventually, how to load key environment settings (as are being developed in #214 ).

## Actual Behavior
There is not yet a Using Theta page. 

## How can this issue be closed?

This issue can be closed with a merged PR that introduces as Using Theta page to the guides at arfc.github.io.

**Comment by munkm** [comment]
I think @gwenchee or @smpark7 would be good options for this issue since they're currently using Theta!

**Comment by munkm** [comment]
@yardasol once you're on Theta you would be a god candidate for this one too.

**Comment by katyhuff** [comment]
This issue is now overcome by events. We no longer need a guide for Theta. We need one for Polaris.
