### ISSUE TITLE
Update "Using Blue Waters" page

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#216]
## I'm submitting a ...
  - [x] feature request

## Expected Behavior
Ideally, the [Using Blue Waters](http://arfc.github.io/manual/guides/bluewaters) page on the arfc site should be 100% correct, link to useful documentation on the bluewaters main pages, and how to load key environment settings (as are being updated in #213  ).

## Actual Behavior
Some of the information is a bit out of date (bahg -> bbcc), a few links are not present, and there is no information on key environment settings for running moltres or serpent.

## How can this issue be closed?

This issue can be closed with a merged PR that updates the Using Blue Waters page in the guides at arfc.github.io.

**Comment by munkm** [comment]
@LukeSeifert does your issue update everything required, or do we need to make a checklist for all of the updates we need on this page?

**Comment by LukeSeifert** [comment]
> @LukeSeifert does your issue update everything required, or do we need to make a checklist for all of the updates we need on this page?

It has been a while since I made the PR, but it should have updated everything required. The links all still work, so I think everything is still up to date.

**Comment by munkm** [comment]
@LukeSeifert and I chatted and we'll close this issue once serpent usage directions are added to the page.

**Comment by munkm** [comment]
@gwenchee I think you mentioned yesterday that something might still be out of date on the Blue Waters guide? If it is, can you mention them here so we can fix them. If not, I think we can close this issue.

**Comment by gwenchee** [comment]
I mentioned that we don't use the dongle for 2FA anymore, instead we use duopush

**Comment by munkm** [comment]
😭 @yardasol I think this issue could be closed. 

Alternatively, should we: 
* Add a note to the guide page that BW is sundowned but we're keeping the page for archival reasons
* Delete all instances of BW from the website?

**Comment by nsryan2** [comment]
Closing because of #291
