### ISSUE TITLE
Add MS Thesis to Zotero

### ISSUE THREAD

**Issue by ZoeRichter** [arfc/arfc.github.io#218]
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [ ] bug report
  - [X] feature request
  - [ ] question

Hi Roberto, Katy and I noticed your MS thesis wasn't in the Zotero, could you add it?

## How can this issue be closed?

Can be closed when your MS thesis is added to the Zotero in the theses folder under group-pubs.  Thanks!

**Comment by robfairh** [comment]
I totally forgot about this. Done! Thanks for the reminder.
