### ISSUE TITLE
Getting Started Guide: Madicken

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#226]
I think you maybe have already done some of this, but if some of it was skipped, here's the Getting Started guide. 
This issue can be closed when everything in the getting started guide has been completed. 

[http://arfc.github.io/manual/guides/](http://arfc.github.io/manual/guides/)

This includes [adding yourself to the website](http://arfc.github.io/manual/guides/website)

Thanks!

**Comment by munkm** [comment]
I've done everything but forgot to close this issue!
