### ISSUE TITLE
Lu is missing from the group webpage

### ISSUE THREAD

**Issue by munkm** [arfc/arfc.github.io#232]
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [ ] bug report
  - [x] feature request
  - [ ] question

## Expected Behavior

All graduate students working in ARFC should appear on the website in current people

## Actual Behavior

Lu Kissinger doesn't appear in the current people!!! 

## Steps to Reproduce the Problem

Check out http://arfc.github.io/people/

## How can this issue be closed?

- [ ] @lkissin2 should follow the instructions here: http://arfc.npre.illinois.edu/manual/guides/website
- [ ] Make a Pull request to this repository.
- [ ] Once you make a Pull Request to this website, @munkm will review it and merge it into the website!
- [ ] This issue can be closed when @lkissin2 appears on the current people page: http://arfc.github.io/people/

**Comment by nsryan2** [comment]
This was addressed by #245, but the website hasn't been rebuilt (?) so they don't show up. @munkm do you know how to do that?

**Comment by yardasol** [comment]
@nsryan2 I'm working on #247 now. It's been sitting for far too long.
