### ISSUE TITLE
Feature: Update Issue templates

### ISSUE THREAD

**Issue by yardasol** [arfc/arfc.github.io#240]
## I'm submitting a ...
  - [ ] bug report
  - [x] feature request
  - [ ] question

GitHub has updated the way they do [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). You can see [PR 75 in arfc/saltproc](https://github.com/arfc/saltproc/pull/75) for an example for what this looks like.

Additionally, the current issue template is hardcoded for bug reports (other than the checklist at the very top). Specifically, it does not have headings that reflect when a user would want to track a feature request or a question. The above linked example addresses this.

I propose that we add issue templates for bugs and feature requests that utilize the new issue template workflow. We should also add an additional issue template for questions since that is an option in the checkboxes at the top of the current issue template.

**Comment by munkm** [comment]
I love this idea!

**Comment by munkm** [comment]
@nsryan2 Do you think you could take the one on?

**Comment by nsryan2** [comment]
I can absolutely make this happen!
