### ISSUE TITLE
Add Gabe and Nick to the current team in the group org

### ISSUE THREAD

**Issue by nsryan2** [arfc/arfc.github.io#263]
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [ ] bug report
  - [x] feature request
  - [ ] question

## Expected Behavior

All members of the group should be in the `current` team in the group org.

## Actual Behavior

Nick (hwacc-y) and Gabe (GabePaciocco) are not on the `current` team.

## Steps to Reproduce the Problem

  1. Check out the [people](https://github.com/orgs/arfc/people) tab in the org.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## How can this issue be closed?

This issue can be closed when Nick and Gabe are added to the team

**Comment by munkm** [comment]
Done! Thank you for the issue!

**Comment by nsryan2** [comment]
Thank you @munkm! I don't know if this is just on my end, but I'm not seeing @GabePaciocco in the current team. Nick is there though
