### ISSUE TITLE
University Logo display error

### ISSUE THREAD

**Issue by hwacc-y** [arfc/arfc.github.io#273]
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

## Expected Behavior
The logo of UIUC should be next to ARFC.

## Actual Behavior
The icon is missing from the header.

## Steps to Reproduce the Problem

  1. Go to arfc.github.io/ 
  2. The error should be present on the header.
  

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## How can this issue be closed?
Replace the icon link (src="https://marketing.illinois.edu/images/brand/design/logo/block-i-primary.png") with a new link to the marketing department's designated logo or download a logo from the marketing department and host the icon image on the website repository.

**Comment by katyhuff** [comment]
closed with #300
