### ISSUE TITLE
Configure Git link broken in setting started manual

### ISSUE THREAD

**Issue by nglaser3** [arfc/arfc.github.io#285]
I was going through the ARFC website, and in the getting started guide the 'configure git' link sent me to a page not found error. 

## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

## Expected Behavior
when clicking on the link you go to a setting up page.

## Actual Behavior
when clicking on https://swcarpentry.github.io/git-novice/02-setup/ you go to a page not found.

## How can this issue be closed?
The link gets fixed

**Comment by munkm** [comment]
Thanks for the bug report @nglaser3 !! I think the link to fix this issue is https://swcarpentry.github.io/git-novice/02-setup.html . The carpentries recently redid their lesson design so now the URL has changed slightly.

**Comment by nsryan2** [comment]
Addressed in #296
