### ISSUE TITLE
MOOC for Eli

### ISSUE THREAD

**Issue by nglaser3** [arfc/arfc.github.io#290]
This repository's issues are reserved for feature requests, and bug reports, and questions.

## I'm submitting a ...
  - [ ] bug report
  - [x] feature request
  - [ ] question

## Expected Behavior
MOOC for reviewing dissertations / thesis / papers / ...

## Steps to Reproduce the Problem

  1. Open the link below, and complete the free version of the course
  1. https://www.coursera.org/learn/sciwrite
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by nsryan2** [comment]
Completed a while ago, confirmed with @ElijahCapps on 9/2.
