### ISSUE TITLE
Update link to book in getting started guide

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#304]
@osanstrong noticed that the old link to the effective computation in physics book is dead. Long live a new link. 

## I'm submitting a ...
  - [x] bug report
  - [ ] feature request
  - [ ] question

## Expected Behavior
The ECIP book link in the getting started guide should go to a real page.

## Actual Behavior
404

## Steps to Reproduce the Problem

  1. Go here
  1. try link to "book"
  1. get nowhere.

## How can this issue be closed?
Replace that link with this one which should work for most folks : https://i-share-uiu.primo.exlibrisgroup.com/permalink/01CARLI_UIU/gpjosq/alma99954930827405899

**Comment by munkm** [comment]
This was resolved by #305
