### ISSUE TITLE
Add OpenMCyclus to software

### ISSUE THREAD

**Issue by abachma2** [arfc/arfc.github.io#306]
This issue requests that OpenMCyclus be added to the list of software on the website. A good link for OpenMCyclus is the repo for it (https://github.com/arfc/openmcyclus). A journal article about it has been submitted to a journal, which will be added via a later issue. 

## I'm submitting a ...
  - [ ] bug report
  - [X] feature request
  - [ ] question

## Expected Behavior
The software list on the website includes OpenMCyclus

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

## How can this issue be closed?

When a PR is merged that adds OpenMCyclus to the list and links to the GitHub.

**Comment by osanstrong** [comment]
Two clarifications on this request (with image example) @abachma2 :

1: Would it be most accurate to denote "Amanda Bachmann" as the original creator (as shown in the images below), or something else? (e.g. multiple contributors, or "ARFC")
2: For logo, would an impromptu concept (such as in the first image) or just the github generated embed (as shown in the second image, and currently used for SaltProc) be preferable?
![image](https://github.com/arfc/arfc.github.io/assets/170151081/a35a1284-4dbe-4c3c-8e21-d295a50f167b)
![image](https://github.com/arfc/arfc.github.io/assets/170151081/5741ba41-5f8f-4576-9040-3813bbaa419f)

**Comment by abachma2** [comment]
Great questions @osanstrong. 
1. Since some of the other software mentions single contributors, I think just listing me wis fine (although I think @katyhuff should have final say on that)
2. That's a really cool impromptu logo you made, but I think using the github generated embed is best. I don't know if the Cyclus and/or OpenMC logos are copyrighted.

**Comment by nsryan2** [comment]
Closed by #317
