### ISSUE TITLE
research/software missing

### ISSUE THREAD

**Issue by jbae11** [arfc/arfc.github.io#31]
The software part of research in the website is missing..?

I think it could be fixed by changing `research/other.md` to `software.md` 

I would've made a PR but I wasn't sure.. do feel free to shoot me down (figure of speech) if I'm wrong.

**Comment by jbae11** [comment]
I also realized that the link to software is `arfc.github.io/software`, not `arfc.githb.io/research/software`

like other research criteria `publications` and `presentations`

**Comment by katyhuff** [comment]
> The software part of research in the website is missing..?
no, it's right here: http://arfc.npre.illinois.edu/software/

> I think it could be fixed by changing research/other.md to software.md

please don't do that. 

> I also realized that the link to software page isarfc.github.io/software, not arfc.githb.io/research/softwarelike other research criteria publications and presentations.

true . not actually a problem though. 

> Accessing the software tab from the top of the page links to arfc.github.io/software (successfully)

yes, it does. 

> but the software link from http://arfc.github.io/research/ takes to arfc.github.io/research/software (404 error)

this is the actual error. Would you like to fix it or should I? It is a one line fix.

**Comment by jbae11** [comment]
#32 PR just in case!

**Comment by jbae11** [comment]
#32 merged
