### ISSUE TITLE
Office 216 Cleanup – Action Needed

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#330]
## I'm submitting a ...
  - [ ] bug report
  - [x] feature request (administrative)
  - [ ] question

## Expected Behavior

Your shared office space, Room 216, should be a tidy, organized haven for concentration and collaboration, with each student feeling comfortable and confident that their environment is healthy, clean, and conducive to productivity. While the janitorial service can be relied upon to empty trash, it is not part of their remit to keep our office spaces clean and tidy. That is up to us, so regular light cleaning and occasional deep cleaning is necessary.  Also, the office needs to be ready to receive a new piece of furniture -- soon, Barb will be helping us to acquire a new bookshelf where shared books and objects can be neatly organized. 

## Actual Behavior

As happens naturally in any working space, the shared office space, Room 216, has become cluttered and needs some attention with regard to dust and disorder. In order to create a more organized and productive environment, I’m asking everyone to dedicate some time to clean and declutter the space. I will acquire some cleaning supplies this weekend and leave them in the office for your use.

## How can this issue be closed?

Below is a checklist of tasks to be completed by the end of next week. I'll come by the office late in the week to review what's been accomplished.

**Office 216 Cleanup Checklist:**

- [x] **Desks & Workstations:**
  - [x] Declutter all desks: Remove unnecessary papers, old notes, and personal items no longer in use.
  - [x] Dust desktops, monitors, and keyboards.
  - [x] Properly organize and secure any loose cables.
  - [x] Wipe down surfaces with appropriate cleaning wipes.

- [x] **Shared Items & Books:**
  - [x] Gather any unclaimed books or shared materials and place them in a designated spot. These items will be organized on the new bookshelf I will be providing soon.
  - [x] Check for any personal belongings of former students and determine what to discard, return to those students, or adopt as a shared resource.

- [x] **Carpet & Floor Cleaning:**
  - [x] Vacuum or sweep the carpet to remove dust and debris. Barb would be delighted to direct you to the department vacuum. 
  - [x] Spot clean any visible stains on the carpet.

- [x] **Electronics:**
  - [x] Organize keyboards, computer mice, and other peripherals. Label anything unclaimed or unused, and discuss whether it’s still needed.
  - [x] Superfluous keyboards, mice, and cables should be organized, dusted, and brought to Barb for redistribution in the office. 
  - [x] Ensure that all cables are neatly managed and not causing a tripping hazard. One or more 25 ft. ethernet cables may be needed to avoid cords that cross the walking path. Barb can provide these. 
   - [x] Some Dell CPUs may no longer be functional. I will open a separate issue for an interested undergraduate to evaluate the health of these devices and either dispose of them (proper protocol requires engagement with Barb and Sarah) or set them up for use.

- [x] **General Tidiness:**
  - [x] Dispose of any trash and recycling materials.
  - [x] Ensure that all shared spaces and unclaimed desks (including draws) are cleared of clutter and cleaned.
  - [x] Consider innovative solutions, even re-arrangements of the space (where should the printer go, are there superior ways to store dry erase markers? how can you make the most of the space in other ways?)

Thank you all for your cooperation!

**Comment by nsryan2** [comment]
Closing with the condition that we bring the box of cables and extras down to Barb tomorrow.

**Comment by katyhuff** [comment]
You folks are the best -- GREAT JOB. Thanks @arfc/current !
