### ISSUE TITLE
Apply for restricted software

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#34]
This issue can be closed when you have applied for the following software.:

- [x] First, register with RSICC (https://rsicc.ornl.gov/Registration.aspx)
- [x] Serpent 1 (go to https://rsicc.ornl.gov/CustomerService.aspx) 
- [x] SCALE 6.2 (go to https://rsicc.ornl.gov/CustomerService.aspx) 
- [ ]  optional: MCNP(go to https://rsicc.ornl.gov/CustomerService.aspx)

**Comment by hzhang21** [comment]
I have registered with RSICC and applied for Serpent 1 and SCALE 6.2.
