### ISSUE TITLE
Andrei Internship Prep

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#53]
- [x] fill out ORNL, ANL, and INL generic applications for Summer 2018 (if they're open)
- [x] update CV and either send it to @katyhuff or upload it somewhere on the web and let me know the link.
- [x] look for papers related to MPACT MSR development.

After these things are done, remind katy to send email introductions.

**Comment by andrewryh** [comment]
@katyhuff I'm about close this issue.
My CV here: https://github.com/andrewryh/CV/blob/master/cv.pdf

Looks like time to send emails to people in National Labs but I know you crazy busy now....

**Comment by katyhuff** [comment]
Looks great. Quick recommendation: On line https://github.com/andrewryh/CV/blob/master/cv.tex#L76 use `` on the left and '' on the right instead of double quotes. LaTeX will handle it better.
