### ISSUE TITLE
Install serpent 2 on blue waters

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#54]
Use only open source cross sections.

**Comment by andrewryh** [comment]
http://www.oecd-nea.org/dbforms/data/eva/evatapes/jeff_32/

**Comment by andrewryh** [comment]
> The cross section libraries in Serpent 1 distribution were generated using NJOY version 99.259.

http://ttuki.vtt.fi/serpent/viewtopic.php?f=15&t=1952&hilit=NJOY&sid=00b740990a73572b117ecc951e966395

**Comment by katyhuff** [comment]
Is this just a note or does it present a blocking problem? I thought the script in serpent could probably turn endf or jeff into ace formatted cross sections without NJOY. Is this not so?

**Comment by andrewryh** [comment]
This is a note but also possible blocking problem :D
ACE files from Serpent package were generated from open-source ENDF/JEFF using NJOY in format usable for MCNP. Perl script in a package just creating like ACE files map for using it in Serpent.
They did so to use one folder with ACE files (which is ~7Gb) both for MCNP and Serpent simultaneously.

My goal now generates the same ACE using files from https://www-nds.iaea.org/public/download-endf/ and NJOY. It is not trivial as I thought.

**Comment by katyhuff** [comment]
good luck.

**Comment by andrewryh** [comment]
@katyhuff Serpent 2 installed on BW and I have created library for only one temperature (900K)...

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/054dd530-0437-42e2-b542-ea3336633e5f-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)
