### ISSUE TITLE
End-of-Semester Individual Meeting

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#67]
Please schedule an end-of-semester individual meeting with me in the month of December. It should last no less than 1 hour.  https://katyhuff.youcanbook.me 

Please also send via email at least a few paragraphs (up to one page) summarizing your progress this semester, your plan for next semester, your projected timeline to graduation (e.g. a GANTT chart), and any questions or concerns that you'd like to address in our meeting.

For you, I think this needs to include a discussion of the review of your prelim draft - which is upcoming, I think?

**Comment by andrewryh** [comment]
No, my draft far far away from close...
Now trying to build PyNE on BW, I have spent half of last week for it.

But I have some thoughts about workflow optimization

**Comment by katyhuff** [comment]
@andrewryh :  just fyi, regarding the draft,  this issue (though otherwise identical to yours) is targeted at @kamuda1 .

 I don't expect a prelim for some time from you andrei -- paper & MS first.

**Comment by andrewryh** [comment]
Sorry, my bad...
