### ISSUE TITLE
Make Gaps Report an ARFC Report

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#69]
@katyhuff will lead this. 

- [x] final edits
- [x] cover sheet 
- [x] number
- [x] DOI (zenodo? figshare? arxiv?)
- [x] add to zotero
- [x] hosted location on website

**Comment by katyhuff** [comment]
@jbae11 : I intentionally assigned myself to this. I would like to establish the formality of this process. You don't need to be assigned to it.

**Comment by jbae11** [comment]
Oh I was just trying to follow the progress, to learn how to do it later on maybe? But I guess now that you've mentioned me i'll be tracking it!

**Comment by katyhuff** [comment]
You can always subscribe to an issue on the right hand side:

![image](https://user-images.githubusercontent.com/393899/33529670-a4c67a9c-d839-11e7-95ce-361c0c160bf8.png)

**Comment by katyhuff** [comment]
I did it! 
http://arfc.npre.illinois.edu/research/reports/ 
github.com/arfc/uiuc-arfc-2017-02
