### ISSUE TITLE
Create Repository for Pyroprocessing Archetype

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#71]
Start with cycstub instructions OR start with separations facility and create your own archetype with details of pyroprocessing. Contemplate signatures and observables that you'll want to write to the output database.

**Comment by katyhuff** [comment]
I forgot. This should probably be done in the recycle repository (but the recycle repository isn't actually ready for submissions... see https://github.com/cyclus/recycle/issues/1 ).

**Comment by katyhuff** [comment]
once recycle is ready for contributions (help @jbae11 make that happen.. he has already begun). ...

Move separations.h and separations.cc into the recycle repository, along with git history ...

This may fail. If so, copy and paste the files. See if you can at least modify authorship on first commit.

**Comment by katyhuff** [comment]
(also the corresponding tests)

**Comment by katyhuff** [comment]
@gtw2 status?

**Comment by katyhuff** [comment]
@gtw2 status?

**Comment by gtw2** [comment]
arfc/recycle has been deleted and reforked from cyclus/recycle. I've created a new branch on my fork called pyre which contains the separations archetype modified to build under recycle.

**Comment by gtw2** [comment]
Should I pull this to arfc and make issues there? @katyhuff

**Comment by katyhuff** [comment]
Yep -- make a PR from your gtw2/recycle (pyre) branch to arfc/recycle (master)

**Comment by katyhuff** [comment]
I think this can be closed?
