### ISSUE TITLE
Create Serpent 2.1.30 module on Blue Waters

### ISSUE THREAD

**Issue by smpark7** [arfc/arfc.github.io#74]
Update for the Serpent module on Blue Waters

**Comment by smpark7** [comment]
Updated and tested by Andrei.

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/430025ee-b231-4e76-b651-9909984b7b68-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)
