### ISSUE TITLE
Add ANS Student Conference  Presentation to the Website

### ISSUE THREAD

**Issue by katyhuff** [arfc/arfc.github.io#78]
Hi Louis, I'd love to highlight your presentation on the website, since it's fairly related to ARFC work. Since this was technically related to your independent study project, you certainly don't have to -- this issue is optional. However, it's nice to have a record of your accomplishments somewhere on the internet. Can you please add your ANS student conference presentation to the website in the presentations section?

**Comment by lkissin2** [comment]
Will do, thanks
